name: maedn
version: '1.0'
main: dev.hufeisen.maedn.MaednMain
api-version: '1.21'
authors: [ Hufeisen ]

commands:
  setup:
    description: Setup the game
    usage: /<command>
    permission: maedn.setup
  start:
    description: Start the game
    usage: /<command>
    permission: maedn.start

permissions:
  maedn.setup:
    description: Allows the player to setup the game
    default: op
  maedn.start:
    description: Allows the player to start the game
    default: op
